---
title: "Laundry Analysis"
author: "Gabe Cederberg"
date: "2/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(tidyverse)
library(lubridate)
library(readxl)
```


```{r, echo = FALSE}
# Merging the sheets into one dataframe

a <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "10 DEWOLFE STREET") %>% 
          mutate(location = "10 DEWOLFE STREET") %>% 
          clean_names()

b <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "1201 MASS AVE 3RD FLR LR") %>% 
          mutate(location = "1201 MASS AVE 3RD FLR LR") %>% 
          clean_names()

c <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "1202 MASS AVE 4TH FLR LR") %>% 
          mutate(location = "1202 MASS AVE 4TH FLR LR") %>% 
          clean_names()

d <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "1306 MASS AVE") %>% 
          mutate(location = "1306 MASS AVE") %>% 
          clean_names()

e <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "20 DEWOLFE STREET") %>% 
          mutate(location = "20 DEWOLFE STREET") %>% 
          clean_names()

f <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "20 PRESCOTT ST") %>% 
          mutate(location = "20 PRESCOTT ST") %>% 
          clean_names()

g <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "22 PRESCOTT ST") %>% 
          mutate(location = "22 PRESCOTT ST") %>% 
          clean_names()


h <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "24 PRESCOTT ST") %>% 
          mutate(location = "24 PRESCOTT ST")%>% 
          clean_names()

i <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "65 MOUNT AUBURN STREET") %>% 
          mutate(location = "65 MOUNT AUBURN STREET")%>% 
          clean_names()

j <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "8 PLYMPTON STREET") %>% 
          mutate(location = "8 PLYMPTON STREET") %>% 
          clean_names()


k <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CABOT HOUSE - BERTRAM HALL") %>% 
          mutate(location = "CABOT HOUSE - BERTRAM HALL")%>% 
          clean_names()

l <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CABOT HOUSE - BRIGGS HALL") %>% 
          mutate(location = "CABOT HOUSE - BRIGGS HALL")%>% 
          clean_names()

m <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CABOT HOUSE - ELLIOT HALL") %>% 
          mutate(location = "CABOT HOUSE - ELLIOT HALL") %>% 
          clean_names()

n <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CABOT HOUSE - WHITMAN HALL") %>% 
          mutate(location = "CABOT HOUSE - WHITMAN HALL")%>% 
          clean_names()

o <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CURRIER HOUSE - BINGHAM HALL") %>% 
          mutate(location = "CURRIER HOUSE - BINGHAM HALL")%>% 
          clean_names()

p <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CURRIER HOUSE - DANIELS HALL") %>% 
          mutate(location = "CURRIER HOUSE - DANIELS HALL") %>% 
          clean_names()


q <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CURRIER HOUSE - GILBERT HALL") %>% 
          mutate(location = "CURRIER HOUSE - GILBERT HALL")%>% 
          clean_names()

r <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CURRIER HOUSE - TUCHMAN HALL") %>% 
          mutate(location = "CURRIER HOUSE - TUCHMAN HALL")%>% 
          clean_names()


s <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "PFORZHEIMER HOUSE - COMSTOCK HA") %>% 
          mutate(location = "PFORZHEIMER HOUSE - COMSTOCK HA") %>% 
          clean_names()


t <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "PFORZHEIMER HOUSE - HOLMES HALL") %>% 
          mutate(location = "PFORZHEIMER HOUSE - HOLMES HALL")%>% 
          clean_names()

u <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "PFORZHEIMER HOUSE - JORDAN NORT") %>% 
          mutate(location = "PFORZHEIMER HOUSE - JORDAN NORT")%>% 
          clean_names()



v <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "PFORZHEIMER HOUSE - JORDAN SOUT") %>% 
          mutate(location = "PFORZHEIMER HOUSE - JORDAN SOUT") %>% 
          clean_names()


w <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "PFORZHEIMER HOUSE - MOORS HALL") %>% 
          mutate(location = "PFORZHEIMER HOUSE - MOORS HALL")%>% 
          clean_names()

x <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "PFORZHEIMER HOUSE - WOLBACH HAL") %>% 
          mutate(location = "PFORZHEIMER HOUSE - WOLBACH HAL")%>% 
          clean_names()

y <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "ADAMS HOUSE") %>% 
          mutate(location = "ADAMS HOUSE") %>% 
          clean_names()


z <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CLAVERLY HALL") %>% 
          mutate(location = "CLAVERLY HALL")%>% 
          clean_names()

aa <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "LOWELL HOUSE D") %>% 
          mutate(location = "LOWELL HOUSE D")%>% 
          clean_names()


bb <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "LOWELL HOUSE G") %>% 
          mutate(location = "LOWELL HOUSE G") %>% 
          clean_names()

cc <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "LOWELL HOUSE N") %>% 
          mutate(location = "LOWELL HOUSE N")%>% 
          clean_names()

dd <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "NEW QUINCY-6TH FLOOR") %>% 
          mutate(location = "NEW QUINCY-6TH FLOOR")%>% 
          clean_names()

ee <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "NEW QUINCY-BASEMENT STUDENT LAU") %>% 
          mutate(location = "NEW QUINCY-BASEMENT STUDENT LAU") %>% 
          clean_names()

ff <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "STONE HALL") %>% 
          mutate(location = "STONE HALL")%>% 
          clean_names()

gg <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "DUNSTER HOUSE") %>% 
          mutate(location = "DUNSTER HOUSE")%>% 
          clean_names()

hh <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "LEVERETT HOUSE F TOWER") %>% 
          mutate(location = "LEVERETT HOUSE F TOWER")%>% 
          clean_names()

ii <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "LEVERETT HOUSE G TOWER") %>% 
          mutate(location = "LEVERETT HOUSE G TOWER")%>% 
          clean_names()

jj <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "LEVERETT HOUSE MCKINLOCK") %>% 
          mutate(location = "LEVERETT HOUSE MCKINLOCK")%>% 
          clean_names()

kk <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "MATHER HOUSE HIGH-RISE") %>% 
          mutate(location = "MATHER HOUSE HIGH-RISE")%>% 
          clean_names()

ll <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "MATHER HOUSE LOW-RISE") %>% 
          mutate(location = "MATHER HOUSE LOW-RISE")%>% 
          clean_names()

mm <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "ELIOT HOUSE J") %>% 
          mutate(location = "ELIOT HOUSE J")%>% 
          clean_names()

nn <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "KIRKLAND HOUSE G") %>% 
          mutate(location = "KIRKLAND HOUSE G")%>% 
          clean_names()

oo <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "KIRKLAND HOUSE J") %>% 
          mutate(location = "KIRKLAND HOUSE J")%>% 
          clean_names()

pp <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "WINTHROP - GORE") %>% 
          mutate(location = "WINTHROP - GORE")%>% 
          clean_names()

qq <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "WINTHROP - STANDISH") %>% 
          mutate(location = "WINTHROP - STANDISH")%>% 
          clean_names()

rr <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "APLEY COURT") %>% 
          mutate(location = "APLEY COURT")%>% 
          clean_names()

ss <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "CANADAY HALL") %>% 
          mutate(location = "CANADAY HALL")%>% 
          clean_names()

tt <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "GREENOUGH HALL") %>% 
          mutate(location = "GREENOUGH HALL")%>% 
          clean_names()

uu <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "HURLBUT HALL") %>% 
          mutate(location = "HURLBUT HALL")%>% 
          clean_names()

vv <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "MATTHEWS HALL") %>% 
          mutate(location = "MATTHEWS HALL")%>% 
          clean_names()

ww <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "STOUGHTON HALL") %>% 
          mutate(location = "STOUGHTON HALL")%>% 
          clean_names()

xx <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "THAYER HALL") %>% 
          mutate(location = "THAYER HALL")%>% 
          clean_names()

yy <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "WELD HALL") %>% 
          mutate(location = "WELD HALL")%>% 
          clean_names()

zz <- read_excel("Copy of LaundryView Data.xlsx", 
        sheet = "WIGGLESWORTH HALL") %>% 
          mutate(location = "WIGGLESWORTH HALL")%>% 
          clean_names()


full_data <- bind_rows(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z,
        aa, bb, cc, dd, ee, ff, gg, hh, ii, jj, kk, ll, mm, nn, oo, pp, qq, rr, ss, tt, uu, vv, ww, xx, yy, zz) %>% 
        select(timestamp = "timestamp",
               day = "day_of_week",
               time = "time_of_day",
               location,
               avail_wash = "available_washers",
               unavail_wash = "unavailable_washers",
               avail_dryers = "available_dryers",
               unavail_dryers = "unavailable_dryers")

save(full_data, file ="data/full_data.Rdata")

full_data %>% 
        mutate(no_washers = ifelse(avail_wash == 0, 1, 0)) %>% 
        group_by(location, time) %>%
        summarize(pct_no_wash = mean(no_washers)) %>% 
        mutate(pct_wash_available = 1 - pct_no_wash)



```


```{r, echo = FALSE}
test <- full_data %>% 
        group_by(time_of_day) %>% 
        mutate(avg_unav = mean(unavailable_washers))
```


```{r, echo = FALSE}
# Running a couple different analyses       
        
# ggplot(test, aes(time_of_day, avg_unav)) + geom_point()
```


```{r, echo = FALSE}
 ggplot(test, aes(x = time_of_day, y = avg_unav)) + geom_col(position = "dodge")
```


```{r, echo = FALSE}
busiest <- full_data %>%
         group_by(location) %>%
         summarize(mean_busy = mean(unavailable_washers)) %>%
         arrange(desc(mean_busy))

actual_busiest <- full_data %>%
         group_by(location) %>%
         summarize(washers = max(available_washers),
                   avg_busy = mean(unavailable_washers),
                   adjusted = (avg_busy / washers)) %>%
         arrange(desc(adjusted)) %>%
         head(10)

actual_busiest
 
ggplot(actual_busiest, aes(time_of_day, avg_unav)) + geom_point()


busiest <- full_data %>%
         filter(location == "22 PRESCOTT ST" |
                location == "20 PRESCOTT ST" |
                location == "ADAMS HOUSE" |
                location == "NEW QUINCY-6TH FLOOR" |
                location == "PFORZHEIMER HOUSE - MOORS HALL" |
                location == "STONE HALL") %>%
         group_by(time_of_day, location) %>%
         summarize(mean_busy = mean(unavailable_washers))

 
ggplot(busiest, aes(time_of_day, mean_busy, color = location)) + 
          geom_line()


prescott22 <- full_data %>%
         filter(location == "22 PRESCOTT ST")
prescott22

xy <- full_data %>% 
        group_by(time_of_day, location) %>%
         summarize(mean_busy = mean(unavailable_washers))
        





ggplot(xy, aes(time_of_day, mean_busy)) +
        facet_wrap(~ location) +
        geom_line()

full_data


full_data %>% 
        

```
```{r}

```



